/*
 * jQuery Textarea Characters Counter Plugin v 2.0
 * Examples and documentation at: http://roy-jin.appspot.com/jsp/textareaCounter.jsp
 * Copyright (c) 2010 Roy Jin
 * Version: 2.0 (11-JUN-2010)
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 * Requires: jQuery v1.4.2 or later
 */
(function(a){a.fn.textareaCount=function(h,k){var o={maxWordSize:-1,maxCharacterSize:-1,originalStyle:"originalTextareaInfo",warningStyle:"warningTextareaInfo",warningNumber:20,displayFormat:"#input characters | #words words"};var h=a.extend(o,h);var q=a(this);a("<div class='charleft'>&nbsp;</div>").insertAfter(q);var s={width:q.width()};var f=i(q);f.addClass(h.originalStyle);f.css(s);var p=0;var m=h.maxCharacterSize;var t=h.maxWordSize;var v=0;var u=0;var r=0;q.bind("keyup",function(w){c()}).bind("mouseover",function(w){setTimeout(function(){c()},10)}).bind("paste",function(w){setTimeout(function(){c()},10)});function c(){f.html(g());if(typeof k!="undefined"){k.call(this,l())}return true}function g(){var y=q.val();var w=y.length;if(h.maxCharacterSize>0){if(w>=h.maxCharacterSize){y=y.substring(0,h.maxCharacterSize)}var z=e(y);var x=h.maxCharacterSize-z;if(!n()){x=h.maxCharacterSize}if(w>x){var A=this.scrollTop;q.val(y.substring(0,x));this.scrollTop=A}f.removeClass(h.warningStyle);if(x-w<=h.warningNumber){f.addClass(h.warningStyle)}p=q.val().length+z;if(!n()){p=q.val().length}r=d(j(q.val()));v=m-p}else{if(h.maxWordSize>0){r=d(j(q.val()));if(r>=h.maxWordSize){y=y.substring(0,j(q.val()).join(" ").lastIndexOf(" "));var A=this.scrollTop;q.val(y);this.scrollTop=A}f.removeClass(h.warningStyle);if(r<=h.warningNumber){f.addClass(h.warningStyle)}r=d(j(q.val()));u=t-r}else{var z=e(y);p=q.val().length+z;if(!n()){p=q.val().length}r=d(j(q.val()))}}return b()}function b(){var w=h.displayFormat;w=w.replace("#input",p);w=w.replace("#words",r);if(m>0){w=w.replace("#max",m);w=w.replace("#left",v)}if(t>0){w=w.replace("#maxwords",t);w=w.replace("#leftwords",u)}return w}function l(){var w={input:p,max:m,left:v,words:r};return w}function i(w){return w.next(".charleft")}function n(){var w=navigator.appVersion;if(w.toLowerCase().indexOf("win")!=-1){return true}return false}function e(x){var y=0;for(var w=0;w<x.length;w++){if(x.charAt(w)=="\n"){y++}}return y}function j(z){var B=z+" ";var C=/^[^A-Za-z0-9]+/gi;var x=B.replace(C,"");var w=rExp=/[^A-Za-z0-9]+/gi;var y=x.replace(w," ");var A=y.split(" ");return A}function d(w){var x=w.length-1;return x}}})(jQuery);