tinyMCE.addI18n('de.jmform_dlg',{
hiddenfields_tab : 'Hidden Fields',
add : 'add',
hidden_fields : 'Hidden Fields',
name_id : 'Name or ID',
actions : 'Actions',
insert_input : 'Formularfeld einf&uuml;gen/&auml;ndern',
insert_select : 'Auswahlliste einf&uuml;gen/&auml;ndern',
insert_textarea : 'Textbereich einf&uuml;gen/&auml;ndern',
general_tab : 'Allgemein',
advanced_tab : 'Erweitert',
general_props : 'Allgemeine Eigenschaften',
advanced_props : 'Erweiterte Eigenschaften',
desc : 'Formular einf&uuml;gen/&auml;ndern',
title : 'Formular einf&uuml;gen/&auml;ndern',
width : 'Breite',
height : 'H&ouml;he',
rows : 'Zeilen',
cols : 'Spalten',
action : 'Aktion',
method : 'Methode',
post : 'POST',
get : 'GET',
target : 'Ziel',
enc : 'Verschl&uml;sselungs-Typ',
src : 'Quelle (src)',
name : 'Name',
value : 'Wert',
defval : 'Vorselektierter Wert',
text : 'Text',
radio : 'Radio',
checkbox : 'Checkbox',
button : 'Button',
file : 'Datei',
password : 'Maskiertes Passwort',
auto: 'Automatisch Validieren',
submit : 'Absenden-Button',
reset : 'Zur&uuml;setzen-Button',
hidden : 'Versteckt',
none : 'Kein',
multi : 'multipart/form-data',
multiple: 'Mehrfach-Selektion erlauben',
options: 'Optionen in der Form "Anzeige=Wert" (1 Set pro Linie)',
onsubmit : 'onsubmit',
onreset : 'onreset',
onfocus : 'onfocus',
onblur : 'onblur',
onchange : 'onchange',
onselect : 'onselect',
onclick : 'onclick',
onkeyup : 'onkeyup',
onkeydown : 'onkeydown',
maxlength : 'Maximale L&auml;nge',
required : 'Erforderlich',
size : 'Gr&ouml;sse',
selsize: 'Anzahl angezeigter Optionen',
type : 'Typ',
checked : 'Angew&auml;hlt',
disabled : 'Gesperrt',
border : 'Rahmen',
elem_title : 'Eigenschaften Formular-Element',
elem_desc : 'Eigenschaften Formular-Element',
elem_type : 'Element-Typ',
input : 'input',
select : 'select',
textarea : 'textarea',
props_desc : 'Formular-Eigenschaften',
bordercolor : 'Rahmen-Farbe',
bgcolor : 'Hintergrund-Farbe',
id : 'ID',
style: 'Stil',
langdir : 'Sprach-Richtung',
langcode : 'Sprach-Code',
mime : 'Target MIME type',
bgimage : 'Hintergrund-Bild',
summary : 'Hinweis',
elem : "Element",
elem_elem : 'Aktuelles Formularfeld aktualisieren',
elem_all : 'Alle Formularfelder des Formulars aktualisieren',
del : 'Formular l&ouml;schen',
checkyes : 'Check box if yes'
});
