tinyMCE.addI18n('en.jmform_dlg',{
hiddenfields_tab : 'Hidden Fields',
add : 'add',
hidden_fields : 'Hidden Fields',
name_id : 'Name or ID',
actions : 'Actions',
insert_input : 'Insert/Modify input element',
insert_select : 'Insert/Modify selection element',
insert_textarea : 'Insert/Modify textarea element',
general_tab : 'General',
advanced_tab : 'Advanced',
general_props : 'General properties',
advanced_props : 'Advanced properties',
desc : 'Inserts/Modify a form',
title : 'Insert/Modify form',
width : 'Width',
height : 'Height',
rows : 'Rows',
cols : 'Columns',
action : 'Action',
method : 'Method',
post : 'POST',
get : 'GET',
target : 'Target',
enc : 'Encryption type',
src : 'Source (src)',
name : 'Name',
value : 'Value',
defval : 'Default selected value',
text : 'text',
radio : 'radio',
checkbox : 'checkbox',
button : 'button',
file : 'file',
password : 'masked password',
auto: 'Auto-validate',
submit : 'submit button',
reset : 'reset button',
hidden : 'hidden',
none : 'None',
multi : 'multipart/form-data',
multiple: 'Mutiple selections allowed',
options: 'Options as "display=value", one set per line',
onsubmit : 'onsubmit',
onreset : 'onreset',
onfocus : 'onfocus',
onblur : 'onblur',
onchange : 'onchange',
onselect : 'onselect',
onclick : 'onclick',
onkeyup : 'onkeyup',
onkeydown : 'onkeydown',
maxlength : 'Maxlength',
required : 'Required',
size : 'Size',
selsize: 'Number of option rows',
type : 'Type',
checked : 'Checked',
disabled : 'Disabled',
border : 'Border',
elem_title : 'Form element properties',
elem_desc : 'Form element properties',
elem_type : 'Element variant',
input : 'input',
select : 'select',
textarea : 'textarea',
props_desc : 'Form properties',
bordercolor : 'Border color',
bgcolor : 'Background color',
id : 'Id',
style: 'Style',
langdir : 'Language direction',
langcode : 'Language code',
mime : 'Target MIME type',
bgimage : 'Background image',
summary : 'Summary',
elem : "Element",
elem_elem : 'Update current element',
elem_all : 'Update all elements in form',
del : 'Delete form',
checkyes : 'Check box if yes'
});
