tinyMCE.addI18n('es.jmform_dlg',{
hiddenfields_tab : 'Campos Ocultos',
add : 'Añadir',
hidden_fields : 'Campos Ocultos',
name_id : 'Nombre o ID',
actions : 'Acciones',
insert_input : 'Insertar/Modificar elementos de input',
insert_select : 'Insertar/Modificar elementos de seleccion',
insert_textarea : 'Insertar/Modificar textarea',
general_tab : 'General',
advanced_tab : 'Advanzado',
general_props : 'Opciones generales',
advanced_props : 'Opciones Avanzadas',
desc : 'Insertar/Modificar formulario',
title : 'Insertar/Modificar formulario',
width : 'Width',
height : 'Height',
rows : 'Filas',
cols : 'Columnas',
action : 'Action',
method : 'Modo',
post : 'POST',
get : 'GET',
target : 'Objetivo',
enc : 'Tipo de encriptacion',
src : 'Codigo (src)',
name : 'Nombre',
value : 'Valor',
defval : 'Valor por defecto',
text : 'Texto',
radio : 'Radio',
checkbox : 'Checkbox',
button : 'Boton',
file : 'Fichero',
password : 'Password enmascarada',
auto: 'Auto-validar',
submit : 'Boton aceptar',
reset : 'Boton reset',
hidden : 'Oculto',
none : 'Ninguno',
multi : 'Multiple/Datos formulario',
multiple: 'Permitir multiseleccion',
options: 'Opciones como "display=value", uno por linea',
onsubmit : 'Al aceptar',
onreset : 'Al resetear',
onfocus : 'Al poner el cursor encima',
onblur : 'Validar al salir del campo',
onchange : 'onchange',
onselect : 'Seleccionado',
onclick : 'Al clicar',
onkeyup : 'Al marcar',
onkeydown : 'Al desmarcar',
maxlength : 'Longitud maxima',
required : 'Obligatorio',
size : 'Tamaño',
selsize: 'Numero de opciones por fila',
type : 'Tipo',
checked : 'Marcado',
disabled : 'Deshabilitado',
border : 'Borde',
elem_title : 'Propiedades del elemento de formulario',
elem_desc : 'Propiedades del elemento de formulario',
elem_type : 'Elementos varios',
input : 'Entrada',
select : 'Seleccionar',
textarea : 'Area de texto',
props_desc : 'Propiedades de formulario',
bordercolor : 'Color del borde',
bgcolor : 'Color de fondo',
id : 'Id',
style: 'Stilo',
langdir : 'DIreccion de idioma',
langcode : 'Codigo de lenguaje',
mime : 'Target MIME type',
bgimage : 'Imagen de fondo',
summary : 'Sumario',
elem : "Elemento",
elem_elem : 'Actualizar elemento actual',
elem_all : 'Actualizar todos los elementos',
del : 'Eliminar formulario',
checkyes : 'Marcar para aceptar'
});
