tinyMCE.addI18n('fr.jmform_dlg',{
hiddenfields_tab : 'Champs invisibles',
add : 'Ajout',
hidden_fields : 'Champs invisibles',
name_id : 'Non ou ID',
actions : 'Actions',
insert_input : 'Ajouter/Modifier un Champ d\'entrée',
insert_select : 'Ajouter/Modifier une Liste de sélection',
insert_textarea : 'Ajouter/Modifier une Zone de texte',
general_tab : 'Général',
advanced_tab : 'Avancé',
general_props : 'Propriétés générales',
advanced_props : 'Propriétés avancées',
desc : 'Ajouter/Modifier un Formulaire',
title : 'Ajouter/Modifier un Formulaire',
width : 'Largeur',
height : 'Hauteur',
rows : 'Lignes',
cols : 'Colonnes',
action : 'Action',
method : 'Méthode',
post : 'POST',
get : 'GET',
target : 'Page cible',
enc : 'Type d\'encryptage',
src : 'Source (src)',
name : 'Nom',
value : 'Valeur',
defval : 'Par défaut, la valeur sélectionnée',
text : 'Texte',
radio : 'Bouton radio',
checkbox : 'Case à cocher',
button : 'Bouton',
file : 'Fichier',
password : 'Mot de passe masqué',
auto: 'Auto-validation',
submit : 'Bouton "Valider"',
reset : 'Bouton "Nettoyer"',
hidden : 'Invisible',
none : 'Aucun',
multi : 'Formulaire multi formats',
multiple: 'Selections multiples autorisées',
options: 'Un option par ligne avec "display=value"',
onsubmit : 'A l\'envoi du formulaire',
onreset : 'Au nettoyage du formulaire',
onfocus : 'Au placement du curseur',
onblur : 'A la sortie du champ',
onchange : 'Au changement de valeur',
onselect : 'A la sélection',
onclick : 'Au click de la souris',
onkeyup : 'Au relâchement d\'une touche',
onkeydown : 'A l\'enfoncement d\'une touche',
maxlength : 'Longueur maximale',
required : 'Obligatoire',
size : 'Taille',
selsize: 'Nombre de lignes affichées',
type : 'Type',
checked : 'Coché',
disabled : 'Décoché',
border : 'Bordure',
elem_title : 'Propriétés du Formulaire',
elem_desc : 'Propriétés du Formulaire',
elem_type : 'Elément variant',
input : 'Entrée',
select : 'Sélection',
textarea : 'Zone de texte',
props_desc : 'Propriétés du Formulaire',
bordercolor : 'Couleur de bordure',
bgcolor : 'Couleur de fond',
id : 'Id',
style: 'Style',
langdir : 'Direction d\'écriture',
langcode : 'Code de la langue',
mime : 'Type MIME de la cible',
bgimage : 'Image de fond',
summary : 'Résumé',
elem : "Elément",
elem_elem : 'Actualiser l\`élément courant',
elem_all : 'Actualiser tous les éléments',
del : 'Supprimer le Formulaire',
checkyes : 'Cocher pour accepter'
});
