tinyMCE.addI18n('sv.jmform_dlg',{
hiddenfields_tab : 'Hidden Fields',
add : 'add',
hidden_fields : 'Hidden Fields',
name_id : 'Name or ID',
actions : 'Actions',
insert_input : 'Infoga/Ändra input element',
insert_select : 'Infoga/Ändra selection element',
insert_textarea : 'Infoga/Ändra textarea element',
general_tab : 'Generell',
advanced_tab : 'Avancerat',
general_props : 'Generella egenskaper',
advanced_props : 'Avancerade egenskaper',
desc : 'Infogar/Ändrar en form',
title : 'Infoga/Ändra form',
width : 'Bredd',
height : 'Höjd',
rows : 'Rader',
cols : 'Kolumner',
action : 'Action',
method : 'Method',
post : 'POST',
get : 'GET',
target : 'Target',
enc : 'Encryption type',
src : 'Källa (src)',
name : 'Namn (name)',
value : 'Värde (value)',
defval : 'Värde på standardmarkering',
text : 'Textbox',
radio : 'Alternativknapp',
checkbox : 'Kryssruta',
button : 'Knapp',
file : 'Fil',
password : 'Lösenordsfält',
auto: 'Automatisk validering av formulär',
submit : 'Skicka knapp',
reset : 'Återställ knapp',
hidden : 'Dolt',
none : 'None',
multi : 'multipart/form-data',
multiple: 'Tillåt att flera alternativ markeras',
checkboxyes : 'Kryssa rutan för ja',
options: 'Alternativ som "display=value", ett alternativ per rad',
onsubmit : 'onsubmit',
onreset : 'onreset',
onfocus : 'onfocus',
onblur : 'onblur',
onchange : 'onchange',
onselect : 'onselect',
onclick : 'onclick',
onkeyup : 'onkeyup',
onkeydown : 'onkeydown',
maxlength : 'Maxlägnd',
required : 'Måste fyllas i',
size : 'Storlek',
selsize: 'Antal rader',
type : 'Type',
checked : 'Förkryssad',
disabled : 'Avstängd (disable)',
border : 'Kantlinje',
elem_title : 'Form element egenskaper',
elem_desc : 'Form element egenskaper',
elem_type : 'Element variant',
input : 'input',
select : 'select',
textarea : 'textarea',
props_desc : 'Form egenskaper',
bordercolor : 'Kantlinjefärg',
bgcolor : 'Bakgrundsfärg',
id : 'Id',
style: 'Style',
langdir : 'Language direction',
langcode : 'Språk kod',
mime : 'Target MIME type',
bgimage : 'Bakgrundbild',
summary : 'Sammanfattning',
elem : "Element",
elem_elem : 'Uppdatera current element',
elem_all : 'Uppdatera alla elements i formen',
del : 'Radera form',
checkyes : 'Check box if yes'
});
